PcelariStorefront/PcelariStorefront/Controllers/CatalogController.cs
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PcelariStorefront.Models.DomainModel;
using PcelariStorefront.DAL.Repository;
using System.Data.Entity;

namespace PcelariStorefront.Controllers
{
    public class CatalogController : BaseController
    {
        [Inject]
        public ProductRepository ProductRepository { get; set; }

        // GET: Catalog
        public ActionResult Index()
        {
            List<User> Merchants = DbContext.Users.Where(u => u.IsBeeKeper).ToList();
            return View(Merchants);
        }

        [HttpGet]
        public ActionResult Products(string uid)
        {
            User usr = DbContext.Users.Where(u => u.Id.Equals(uid)).First();
            List<Product> products = DbContext.Products.Include(pt => pt.ProductType).Where(p => p.UserId == usr.UserName && p.Quantity > 0).ToList();
            return View(products);
        }
    }
}

PcelariStorefront/PcelariStorefront/Controllers/MOrderController.cs
using Ninject;
using PcelariStorefront.DAL.Repository;
using PcelariStorefront.Models.DomainModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PcelariStorefront.Controllers
{
    public class MOrderController : BaseController
    {
        [Inject]
        public OrderRepository OrderRepository { get; set; }

        // GET: MOrder
        public ActionResult Index()
        {
            List<OrderProduct> myOrderProducts = DbContext.OrderProducts.Where(op => op.MerchantId == UserId).ToList();
            List<Order> myOrders = new List<Order>();

            foreach(OrderProduct op in myOrderProducts)
            {
                Order o = OrderRepository.Find(op.OrderId);
                myOrders.Add(o);
            }

            List<Order> model = myOrders.Distinct().OrderBy(o => o.DateCreated).ToList();

            return View(model);
        }
    }
}

PcelariStorefront/PcelariStorefront/Controllers/ProductController.cs
using Ninject;
using PcelariStorefront.DAL.Repository;
using PcelariStorefront.Models.DomainModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PcelariStorefront.Controllers
{
    public class ProductController : BaseController
    {
        [Inject]
        public ProductRepository ProductRepository { get; set; }

        // GET: Product
        public ActionResult Index()
        {
            List<Product> modelForView = DbContext.Products
                                            .Include(pt => pt.ProductType)
                                            .Where(prod => prod.UserId == UserId)
                                            .ToList();
            if (modelForView != null)
                return View(modelForView);
            else return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            this.GetPossibleTypes();
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            this.GetPossibleTypes();
            Product model = ProductRepository.Find(id);
            return View(model);
        }

        [HttpGet]
        [Route(Name = "Obrisi_Proizvode")]
        public ActionResult Delete(int id)
        {
            this.ProductRepository.Delete(id, autoSave: true);
            return View("Index");
        }

        [HttpPost]
        public ActionResult Create(Product model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedByUser = UserId;
                model.UserId = UserId;
                this.ProductRepository.Add(model, autoSave: true);

                return RedirectToAction("Index");
            }
            else
            {
                this.GetPossibleTypes();
                return View(model);
            }
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditProduct(int id)
        {
            var model = this.ProductRepository.Find(id);

            var didUpdateModelSucceed = this.TryUpdateModel(model);

            if (didUpdateModelSucceed && ModelState.IsValid)
            {
                model.ModifiedByUser = UserId;
                this.ProductRepository.Update(model, autoSave: true);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        private void GetPossibleTypes()
        {
            var possibleTypes = DbContext.ProductTypes.ToList();
            var selectItems = new List<System.Web.Mvc.SelectListItem>();

            //Polje je opcionalno
            var listItem = new SelectListItem();
            listItem.Text = "- odaberite -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var type in possibleTypes)
            {
                listItem = new SelectListItem();
                listItem.Text = type.Name;
                listItem.Value = type.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }

            ViewBag.PossibleTypes = selectItems;
        }
    }
}

PcelariStorefront/PcelariStorefront/Controllers/UOrderController.cs
using PcelariStorefront.Models.DomainModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PcelariStorefront.Controllers
{
    public class UOrderController : BaseController
    {
        // GET: MOrder
        public ActionResult Index()
        {
            List<Order> myOrders = DbContext.Orders.Where(o => o.UserId == UserId).ToList();
            return View(myOrders);
        }
    }
}

PcelariStorefront/PcelariStorefront/Views/Shared/_Layout.cshtml
@using Pcelaristorefront.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bee products store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bee products store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @using (Html.BeginAuthLi("Admin"))
                    {
                        @Html.ActionLink("Admin", "Index", "Admin", new { area = "Admin" }, new { })
                    }
                    @using (Html.BeginAuthLi("BeeKeeper"))
                    {
                        @Html.ActionLink("Products", "Index", "Product")
                    }
                    @using (Html.BeginAuthLi("BeeKeeper"))
                    {
                        @Html.ActionLink("Merchant Orders", "Index", "MOrder")
                    }
                    @using (Html.BeginAuthLi("BeeKeeper"))
                    {
                        @Html.ActionLink("Merchant Payments", "Index", "MPayment")
                    }
                    @using (Html.BeginAuthLi("StandardUser"))
                    {
                        @Html.ActionLink("Product catalog", "Index", "Catalog")
                    }
                    @using (Html.BeginAuthLi("StandardUser"))
                    {
                        @Html.ActionLink("My Orders", "Index", "UOrder")
                    }
                    @using (Html.BeginAuthLi("StandardUser"))
                    {
                        @Html.ActionLink("My Payments", "Index", "UPayment")
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bee Products store - .NET Okruženje</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/globalize")
    @Scripts.Render("~/bundles/bootstrap")
    @Html.Partial("_UICultureSetup")
    @RenderSection("scripts", required: false)
</body>

</html>

PcelariStorefront/PcelariStorefront/Views/Shared/_UICultureSetup.cshtml
@{ 
    var culture = System.Threading.Thread.CurrentThread.CurrentCulture;
    var cultureCode = culture.TwoLetterISOLanguageName;
    var jsDatePattern = culture.DateTimeFormat.ShortDatePattern.ToUpper();
}

<script type="text/javascript">
    $(function () {
        $('.date-picker').datetimepicker({
            locale: '@cultureCode',
            format: '@jsDatePattern'
        });
    });
</script>

<script type="text/javascript">
    $.validator.methods.date = function (value, element) {
        if (this.optional(element) && (value == '' || value == undefined || value == null))
            return true;

        var shortDatePattern = '@jsDatePattern';

        return moment(value, shortDatePattern).isValid();
    }

    $.when(
      $.get("/scripts/cldr/data/@cultureCode/numbers.json"),
      $.get("/scripts/cldr/data/likelySubtags.json"),
      $.get("/scripts/cldr/data/numberingSystems.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });

    }).then(Globalize.load).then(function () {

        var globalizeNumberParser = Globalize('@cultureCode').numberParser();

        $.validator.methods.number = function (value, element) {
            if (this.optional(element))
                return true;

            if (!isNaN(globalizeNumberParser(value)))
                return true;

            return false;
        }

        $.validator.methods.range = function (value, element, param) {
            if (this.optional(element))
                return true;

            var val = globalizeNumberParser(value);

            return val >= param[0] && val <= param[1];
        }
    });
</script>